---
# VARIABLES
# {X} : Player's X coordinate
# {Y} : Player's Y coordinate
# {Z} : Player's Z coordinate
# {NAME} : Player's Name
# {WORLD} : The Name of the world the player is in
# {N} : Next Line/Break Line
# {PLAYERS} : Number of players online
# {MONEY} : Player's money. (Must have EconomyAPI)
# {FACNAME} : Player's Faction Name
# {FACPOWER} : Player's Faction Power
# {MAXPLAYERS} : Shows server max number of players
# {HEALTH} : Shows Player's current health
# {MAXHEALTH} : Shows Player's max health

Messages:
  - "§l§bX-Hud"
  - "§l§cX-Hud"
  - "§l§aX-Hud"
  - "§l§eX-Hud"
  - "§l§dX-Hud"
  
...
